sudo: required

notifications:
  email: false

language: node_js
cache: yarn

node_js:
  - "8"
  - "10"
  - "12"

services:
  - docker

env:
  global:
    # Default scality/s3server credentials
    - AWS_ACCESS_KEY_ID=accessKey1 AWS_SECRET_ACCESS_KEY=verySecretKey1

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_install:
  - docker run -d --name s3server -p 8000:8000 scality/s3server:mem-latest

install:
  - yarn

script:
  - commitlint-travis
  - yarn run build
  - yarn run format:verify
  - yarn run lint
  - yarn test

after_success:
  - yarn exec semantic-release
