sudo: required

notifications:
  email: false

language: node_js
cache: yarn

node_js:
  - "8"
  - "10"
  - "12"

services:
  - docker

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

env:
  global:
    - AWS_ACCESS_KEY_ID=accessKey1 AWS_SECRET_ACCESS_KEY=verySecretKey1

before_install:
  - >
    docker run
    -d
    --name cloudserver
    -p 8000:8000
    -e S3BACKEND=mem
    -e SCALITY_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    -e SCALITY_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    zenko/cloudserver

install:
  - yarn

script:
  - commitlint-travis
  - yarn run build
  - yarn run format:verify
  - yarn run lint
  - yarn test

after_success:
  - yarn exec semantic-release
