sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

env:
  # Default scality/s3server credentials
  - AWS_ACCESS_KEY_ID=accessKey1 AWS_SECRET_ACCESS_KEY=verySecretKey1

before_install:
  - docker run -d --name s3server -p 8000:8000 scality/s3server:mem-latest

script:
  - yarn format:verify
  - yarn lint
  - yarn test
