sudo: required

notifications:
  email: false

language: node_js
cache: yarn

node_js:
  - "8"
  - "10"

services:
  - docker

env:
  global:
    # Amend greenkeeper lockfile update commits to the version bump
    - GK_LOCK_COMMIT_AMEND=true
    # Default scality/s3server credentials
    - AWS_ACCESS_KEY_ID=accessKey1 AWS_SECRET_ACCESS_KEY=verySecretKey1

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_install:
  - docker run -d --name s3server -p 8000:8000 scality/s3server:mem-latest
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn run build
  - yarn run format:verify
  - yarn run lint
  - yarn test

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - yarn exec semantic-release
